question_data = [
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "Peter Molyneux was the founder of Bullfrog Productions.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
          "question": "Snakes and Ladders was originally created in India?",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
          "difficulty": "easy",
          "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "The music group Daft Punk got their name from a negative review they recieved.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "The Great Wall of China is visible from the moon.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in "
                      "fights&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
          "difficulty": "easy",
          "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder "
                      "Tom Anderson.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "It is automatically considered entrapment in the United States if the police sell you illegal "
                      "substances without revealing themselves.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Politics", "type": "boolean", "difficulty": "easy",
          "question": "In 2016, the United Kingdom voted to stay in the EU.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "History", "type": "boolean", "difficulty": "easy",
          "question": "The United States was a member of the League of Nations.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional "
                      "computing power instead of batteries.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Mythology", "type": "boolean", "difficulty": "easy",
          "question": "According to Greek Mythology, Zeus can control lightning.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
          "question": "An atom contains a nucleus.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis "
                      "with a disc drive.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "Minecraft can be played with a virtual reality headset.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness "
                      "Vest&quot;",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "Pluto is a planet.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in "
                      "1990. ",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
          "difficulty": "easy",
          "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
          "question": "There is a Donald Trump Board Game, which was made in 1989.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
          "question": "&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan "
                      "Doyle books of Sherlock Holmes.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
          "difficulty": "easy",
          "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king "
                      "of Hawaii.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "The Windows ME operating system was released in the year 2000.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "George Lucas directed the entire original Star Wars trilogy.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Politics", "type": "boolean", "difficulty": "easy",
          "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We "
                      "Can&quot;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "Daft Punk originated in France.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "Stevie Wonder&#039;s real name is Stevland Hardaway Morris.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Animals", "type": "boolean", "difficulty": "easy",
          "question": "Cats have whiskers under their legs.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "easy",
          "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert "
                      "Hitler away from Normandy\/D-day landing.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "easy",
          "question": "Adolf Hitler was tried at the Nuremberg trials.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Geography", "type": "boolean", "difficulty": "easy",
          "question": "Rhode Island is actually located on the US mainland, despite its name.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
          "question": "A scalene triangle has two sides of equal length.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
          "question": "An equilateral triangle always has every angle measuring 60&deg;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Animals", "type": "boolean", "difficulty": "easy",
          "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
]
